import Context from "./components/Context";
import "./globals.css";
import Footer from "./share/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body
        className={` antialiased`}
      >
        <Context>
          {children}
          <Footer/>
        </Context>
      </body>
    </html>
  );
}
